Entity Data Model Changes to enable PATCH Functionality
companieshouse/psc-filing-api pull request #64
Opened 2023-03-23 15:00 UTC by eedwards0

DO NOT merge with current PSC Filing Service Release 6 - PSC-163

2023-03-27 07:43 UTC, PhilipGlover reviewed
- I've run and submitted all requests for individual and corporate-entity
- all tests pass
- code looks good
- happy to approve once Rel 6 done

2023-03-30 09:28 UTC, hepsimo requested changes
Changes look good. Some very minor fixes recommended.

2023-03-30 09:28 UTC, hepsimo commented on src/main/java/uk/gov/companieshouse/pscfiling/api/model/entity/PscIndividualFiling.java
Please move these to after the getter methods to be more consistent with the other classes

2023-03-30 09:28 UTC, hepsimo commented on src/main/java/uk/gov/companieshouse/pscfiling/api/model/entity/PscIndividualFiling.java
>      }
Please remove this redundant builder call, but keep the public constructor and the comment

2023-03-30 09:28 UTC, hepsimo commented on src/main/java/uk/gov/companieshouse/pscfiling/api/model/entity/PscIndividualFiling.java
>                  .add("countryOfResidence='" + countryOfResidence + "'")
These lines can be replaced with
`.add(super.toString())`

2023-03-30 09:55 UTC, hepsimo approved these changes
Changes look good

2023-03-30 10:54 UTC, merged